
version: '3.4'

services:
  cableql:
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    container_name: cableql
    build: ./
    image: josephsiefers/cableql
    volumes:
      - ./:/home/app
    ports:
      - "127.0.0.1:3003:3000"